language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install -y pycodestyle
    - conda install --yes python=3.6
    - conda install --yes numpy
    - conda install --yes matplotlib
      
script:
    - chmod +x test_box.sh
    - chmod +x test_func_get_gene_counts.sh
    - chmod +x test_get_tissue_samples.sh
    - ./test_box.sh
    - ./test_func_get_gene_counts.sh
    - ./test_get_tissue_samples.sh
